baseURL = 'https://ise.cx'
languageCode = 'en-us'
title = 'isecx'
theme = "../../../advert-ise"
[params]
  description = "World Wide Website of Ise ChannelX"

[markup.goldmark.renderer]
  unsafe = true
